var tipos_travel_extra = {
    0: "Aventura",
    1: "Actividades acuaticas",
    2: "Cena",
    3: "Boletos",
    4: "Golf",
    5: "Transfers",
    6: "Otros servicios",
    7: "Paseos de compras",
    8: "Spa",
    9: "Tours y Excursiones",
    10: "Parques de atracciones",
    11: "Casamientos",
    12: "Actividades de Golf",
    13: "Extras de Aereos",
    14: "Cobro a tarjetas de credito",
    15: "Actividades de Ski",
    16: "Boletos de Aerosilla",
    17: "Tren",
    18: "Seguro de viaje",
    19: "Visa",
    20: "Bus",
    21: "Cena Show",
    22: "City Tour",
    23: "Comida",
    24: "Entrevistas",
    25: "Show",
    26: "Almuerzo",
    27: "Traslado Aereo",
    28: "Curso",
    29: "Campamento",
    30: "Paquete"
}